### ISSUE TITLE
Multiple bugs in SH-FWI

### ISSUE THREAD

**Issue by daniel-koehn** [daniel-koehn/DENISE-Black-Edition#10]
The current implementation of SH-FWI in DENISE Black-Edition contains multiple bugs, which prevent a successfull FWI. Therefore, you have to use the stable SH-FWI code DENISE_SH

**Comment by PavelPlotnitskii** [comment]
Hi, Daniel!
I have question about two lines in denise.c file.
There are some forced assigning of QUELLART variable in rows:
https://github.com/daniel-koehn/DENISE-SH/blob/429c519a8bf8240989f9f941cef38298b879f803/src/denise.c#L893
https://github.com/daniel-koehn/DENISE-SH/blob/429c519a8bf8240989f9f941cef38298b879f803/src/denise.c#L1070

Does it make sense to leave QUELLART=3 or 6, if I want to use ricker wavelet with parameters from file with source coordinates?

**Comment by daniel-koehn** [comment]
Hi Pavel,

The forced QUELLART settings are limited to the source wavelet estimation part of DENISE. QUELLART = 6 forces the calculation of a bandlimited Green's function, required for the Wiener deconvolution. QUELLART=3 reads the estimated source wavelets from the ASCII files. 

If you do not want to use source wavelet estimation, but instead a known Ricker wavelet, you can simply turn off the source wavelet inversion in the DENISE-SH workflow file:
https://github.com/daniel-koehn/DENISE-SH/blob/master/par/FWI_workflow_SH_karlsgraben.inp 
by seting STF_INV=0. To use the Ricker wavelet set QUELLART=1 in 
https://github.com/daniel-koehn/DENISE-SH/blob/master/par/DENISE_SH_karlsgraben.inp
Do not forget to specifiy the center frequency of the Ricker wavelet in column 5 of the source file:
https://github.com/daniel-koehn/DENISE-SH/blob/master/par/source/source_SH.dat
for each source position.

Best regards,

Daniel
