### ISSUE TITLE
Segmentation fault with READREC==2

### ISSUE THREAD

**Issue by ar4** [daniel-koehn/DENISE-Black-Edition#12]
Setting READREC==2 causes a segmentation fault.

When doing forward modeling, this occurs at
https://github.com/daniel-koehn/DENISE-Black-Edition/blob/74b57f25bdb7ff667ab6a37fa430acafd5745ebe/src/PSV/FD_PSV.c#L387

When doing FWI, this occurs at
https://github.com/daniel-koehn/DENISE-Black-Edition/blob/74b57f25bdb7ff667ab6a37fa430acafd5745ebe/src/PSV/FWI_PSV.c#L928

**Comment by daniel-koehn** [comment]
Thanks for the bug report, I fixed the issue related to READREC==2 in the PSV, SH, AC, TTI and VTI modules of DENISE Black-Edition
