### ISSUE TITLE
FP used uninitialized when READREC==2

### ISSUE THREAD

**Issue by ar4** [daniel-koehn/DENISE-Black-Edition#13]
`FP` is declared at:
https://github.com/daniel-koehn/DENISE-Black-Edition/blob/74b57f25bdb7ff667ab6a37fa430acafd5745ebe/src/PSV/obj_psv.c#L24

and then used uninitialized when `READREC==2` at:
https://github.com/daniel-koehn/DENISE-Black-Edition/blob/74b57f25bdb7ff667ab6a37fa430acafd5745ebe/src/PSV/obj_psv.c#L57

**Comment by daniel-koehn** [comment]
Thanks for the bug report. I set the file pointer FP to stdout in the obj_xx.c codes of the DENISE SH, AC and PSV modules.
