### ISSUE TITLE
issue with using source wavelet in ASCII format

### ISSUE THREAD

**Issue by ya-andrey** [daniel-koehn/DENISE-Black-Edition#18]
I have an issue with external wavelet file import (QUELLART=3) in DENISE MODE= 0 and = 1. Appears "R U N - T I M E  E R R O R:  Source file could no be opened !". File in ASCII format with one sample per line, sample interval and number of samples corresponds to the specified in the "DENISE***.inp" file. Log files attached.

[DENISE.out.txt](https://github.com/daniel-koehn/DENISE-Black-Edition/files/3231708/DENISE.out.txt)
[US.log.1.txt](https://github.com/daniel-koehn/DENISE-Black-Edition/files/3231709/US.log.1.txt)

**Comment by daniel-koehn** [comment]
Hi,

There could be multiple reasons for this issue:

1. You have not defined the correct directory of the source wavelet in the DENISE input file (line 43)

https://github.com/daniel-koehn/DENISE-Black-Edition/blob/master/par/DENISE_marm_OBC.inp#L43

Notice that you should use the filename without extension.

2. Another issue might be that in the recent DENISE version you have to define a source wavelet for each source position using the following name convention for each wavelet file:

<SIGNAL_FILE>_shot_<shotnumber>.dat

where SIGNAL_FILE denotes the string (directory and filename) you defined in line 43 of the DENISE input file and shotnumber obviously the shotnumber.

If you want to use the same source wavelet for each shot, you have to modify line 28 in /src/wavelet.c:

https://github.com/daniel-koehn/DENISE-Black-Edition/blob/master/src/wavelet.c#L28

from 

sprintf(signal_wave,"%s_shot_%i.dat",SIGNAL_FILE,ishot);

to 
 
sprintf(signal_wave,"%s.dat",SIGNAL_FILE);

and recompile the source code.

Best regards,

Daniel

**Comment by ya-andrey** [comment]
Thank you for your prompt reply. Changing the wavelet.c file has helped.

**Comment by lltfj1314** [comment]
perfect reply!!!!
