### ISSUE TITLE
2D time domain acoustic FWI

### ISSUE THREAD

**Issue by AlbertZhangHIT** [daniel-koehn/DENISE-Black-Edition#19]
Hi Daniel,

Is there any implementation of 2D time domain acoustic FWI for totally freshman to dive into the field of FWI?

Thank you very much.

**Comment by daniel-koehn** [comment]
Hi Albert,

As tutorial to time domain acoustic FWI, I recommend Devito:

https://www.devitoproject.org/

The authors compiled a tutorial series in "The Leading Edge" together with multiple 
Jupyter notebooks: 

Part 1: Forward modeling
https://www.researchgate.net/publication/321348646_Full-waveform_inversion_Part_1_Forward_modeling
https://github.com/seg/tutorials-2017/tree/master/1712_FWI_forward_modeling

Part 2: Adjoint modeling
https://www.researchgate.net/publication/322132319_Full-waveform_inversion_Part_2_Adjoint_modeling
https://github.com/seg/tutorials-2018/tree/master/1801_FWI_Adjoint_modeling

Part 3: Optimization
https://www.researchgate.net/publication/322901034_Full-waveform_inversion_Part_3_Optimization
https://github.com/seg/tutorials-2018/tree/master/1802_FWI_Inversion

Best regards,

Daniel

**Comment by AlbertZhangHIT** [comment]
Hi Daniel, Thank you so much for your kind help. Best wishes. Albert Albert Zhang 邮箱：albert.zhang.hit@gmail.com 签名由 网易邮箱大师 定制 On 06/20/2019 14:33, Daniel Köhn wrote: Closed #19. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
