### ISSUE TITLE
Visco-Elastic modelling

### ISSUE THREAD

**Issue by lltfj1314** [daniel-koehn/DENISE-Black-Edition#21]
Hi Dr. Daniel,

I am trying to model visco-elastic wave by changing Qs and Qp，but the modelling data do not change with Qs and Qp.  I am sure "L=1" in my modelling. Why that happen? Looking forward to your reply. Thank You!!

Best 
Liu

**Comment by lltfj1314** [comment]
I made it. Mute Lines 106-107 in readmod_visc_psv.c, which set qp and qs are constants.

Thanks

**Comment by daniel-koehn** [comment]
Hi Liu,

Thank you for remembering me to remove the constant qp and qs values from readmod_visc_psv.c. 
=;-)

To achieve a constant Q for a given frequency range, I recommend to use at least L=4 relaxation mechanisms. Optimum relaxation frequencies FL can be calculated using the Matlab codes in the "viscoelasticity" sub-directory in the BIRGIT pre-/postprocessing code:

https://github.com/daniel-koehn/BIRGIT/tree/master/BIRGIT/viscoelasticity

Best regards,

Daniel

**Comment by lltfj1314** [comment]
Hi Dr.Daniel ,

I got you! Thank you! learned a lot from the your works! Great job!

Best 
Liu

**Comment by lltfj1314** [comment]
Hi Dr.Daniel ,

I got you! Thank you! learned a lot from  your works! Great job!

Best
Liu
