### ISSUE TITLE
Topography

### ISSUE THREAD

**Issue by gaoyajian** [daniel-koehn/DENISE-Black-Edition#27]
Hey, dear Daniel, 

I am a new user for your codes, I am wondering can I set a relief topography for the simulations?

Many thanks!

**Comment by daniel-koehn** [comment]
Hi gaoyalian,

The implementation of a relief topography by using vertically deformed meshes, like the one described in this paper:

[Puente et al. (2014) Mimetic seismic wave modeling including topography on deformed staggered grids](https://www.researchgate.net/publication/261286023_Mimetic_seismic_wave_modeling_including_topography_on_deformed_staggered_grids)

is on my ToDo list, but not implemented, yet. You can force a free-surface boundary condition in the DENISE code 
by using the Improved Vaccumm Formulation (IVF):

[Zeng et al. (2012) An improved vacuum formulation for 2D finite-difference modeling of Rayleigh waves including surface topography and internal discontinuities](https://library.seg.org/doi/10.1190/geo2011-0067.1)

and spatially discretize the free surface topography sufficiently.

Best regards,

Daniel
