### ISSUE TITLE
Save custom taper binaries to par/ directory

### ISSUE THREAD

**Issue by ovcharenkoo** [daniel-koehn/DENISE-Black-Edition#31]
Hi everyone,

When creating custom taper geometries, the code searches for them in the directory from where the code was launched, all other data files are fetched from the respective par/ folder. 

The experiment setup would be much more homogeneous if the data attributed to the same experiment would be stored in the same par/ folder.

Now you need to put tapers like this if starting simulations from this level (not from inside par folder):
```
bin/
...
par1/
par2/
taper.bin
taper_u.bin
taper_rho.bin
```

Would be better if like this (all experiment-specific tapers inside par folders):
Now you need to put tapers like this if starting simulations from this level (not from inside par folder):
```
bin/
...
par1/
----taper.bin
----taper_u.bin
----taper_rho.bin
par2/
```

Best regards,
Oleg

**Comment by daniel-koehn** [comment]
Hi Oleg,

Thanks for pointing to this issue. Similiar to the model files, I will add an option to define in which folder the taper files are located to the DENISE parameter file in the next update. I will also add additional parameters which are currently hard-coded in the source code.

Best regards,

Daniel

**Comment by daniel-koehn** [comment]
Hi Oleg,

Just submitted a few DENISE updates to the Github repository - nothing tested yet. ;-)

- I added a basename for taper files in the DENISE parameter file:

https://github.com/daniel-koehn/DENISE-Black-Edition/blob/500a8de8550e475da7dbe7bc12fa3811a5245f50/par/DENISE_marm_OBC.inp#L158

All exported taper files generated within DENISE will also be written to the taper directory.

- I added a parameter GRAD_FORM in the DENISE parameter file:

https://github.com/daniel-koehn/DENISE-Black-Edition/blob/500a8de8550e475da7dbe7bc12fa3811a5245f50/par/DENISE_marm_OBC.inp#L137

which will allow to switch between different gradient formulations, require time integration of the adjoint sources (GRAD_FORM=1) and no time integration of the adjoint sources (GRAD_FORM=2).

- I played around with Random Objective Waveform Inversion according to Pan & Gao (2020), which randomly  
picks either the L2-norm or AGC-norm at each FWI iteration, for which I added a switch ROWI in the DENISE workflow file:

https://github.com/daniel-koehn/DENISE-Black-Edition/blob/master/par/FWI_workflow_marmousi.inp

I have not added the new parameters to the PythonAPI, so this will require some slight modifications, before running correctly. 
For now, I will check if DENISE Black-Edition is still running.

Best regards,

Daniel

**Comment by ovcharenkoo** [comment]
Thanks a lot, will try it out! 

There should not be any modifications needed for the Python API, at least from the parser side. It should fetch all the new parameters from the .inp file on its own. I will add a proper routing for the new taper directory

Best regards,
Oleg
