### ISSUE TITLE
I can't find DENISE.inp in folder /DENISE/par

### ISSUE THREAD

**Issue by z981201** [daniel-koehn/DENISE-Black-Edition#32]
I've done the installation by reading `manual_denise.pdf`. And section 5.4 "Running the program" says I should have a `DENISE.inp` and `FWI_workflow.inp` in folder `/par`. However I only have `DENISE_marm_OBC.inp`, `FWI_workflow_marmousi.inp` and `RTM_workflow_marmousi.inp` three `.inp` files, the same in https://github.com/daniel-koehn/DENISE-Black-Edition/tree/master/par.

I've changed the filename `DENISE_marm_OBC.inp` to `DENISE.inp` and `FWI_workflow_marmousi.inp` to `FWI_workflow.inp`, and ran 
```
mpirun -np 8 ../bin/denise DENISE.inp FWI_workflow.inp
```
It gave an `RUN-TIME ERROR` output below:
```
[iampora@localhost par]$ mpirun -np 8 ../bin/denise DENISE.inp FWI_workflow.inp
 *******************************************************************************
 This is program DENISE Black-Edition                                           
 Parallel 2-D elastic Finite Difference FWI code                                
                                                                                
 Forward/FWI/RTM codes written by D. Koehn and D. De Nil                        
 2D isotropic PSV forward code partly based on FDVEPS written by T. Bohlen      
 Institute of Geosciences, Kiel University, Germany                           

 See README.md file and LICENSE.md for redistribution conditions.               
 *******************************************************************************


 **Message from check_model_phys (printed by PE 0):

 -----------------------  DENISE operation mode  ----------------------
 MODE=0: Only forward modeling is applied.


 -----------------------  DENISE Physics  ----------------------
 PHYSICS=1: Solve 2D isotropic elastic PSV problem.


In FD_PSV MYID = 0, COLOR =0, MYID_SHOT = 0 
 This is the log-file generated by PE 0 

Message from PE 0
R U N - T I M E  E R R O R: 
Number of processors specified in the parameter file 
 and at command line (NP) differ !
...now exiting to system.
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[iampora@localhost par]$ mpirun -np 8 ../bin/denise DENISE.inp FWI_workflow.inp > DENISE.out
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

So where should I get those two `.inp` files and how should I run the example program?

**Comment by daniel-koehn** [comment]
For the Marmousi-2 example DENISE.par is equal to DENISE_marm_OBC.inp. The error message is related to the number of cores you are using. The total number of processors should be equal to the product of the parameters NPROCX * NPROCY, defined in line 15 & 16 of DENISE_marm_OBC.inp:

https://github.com/daniel-koehn/DENISE-Black-Edition/blob/500a8de8550e475da7dbe7bc12fa3811a5245f50/par/DENISE_marm_OBC.inp#L15

In your case you have to set NPROCX = 4, NPROCY =2, resulting in NPROC = NPROCX * NPROCY = 8. For further details how you can decompose your Cartesian FD grid, I refer to the user manual.

Best regards,

Daniel
