### ISSUE TITLE
There is no such file

### ISSUE THREAD

**Issue by LongyanU** [daniel-koehn/DENISE-Black-Edition#35]
https://github.com/daniel-koehn/DENISE-Benchmark/raw/master/Marmousi-II/start/marmousi_II_marine.vp

**Comment by daniel-koehn** [comment]
Hi LongyanU,

I do not understand what the issue is, the model file marmousi_II_marine.vp is part of the DENISE-Benchmark repository. You actually added a link. Therefore, it obviously does exist.

Best regards,

Daniel
