### ISSUE TITLE
Seeking Guidance on Adapting DENISE Black Edition for Field Data Processing in Elastic Wave FWI and LSRTM

### ISSUE THREAD

**Issue by zhangxiaoshuotttt** [daniel-koehn/DENISE-Black-Edition#43]
Hi Daniel,

 I recently came across your excellent open-source code, DENISE Black Edition, which I believe will be extremely helpful for my master's thesis project, as I need to perform FWI and LSRTM of elastic waves.

Firstly, I would like to express my gratitude for your contribution to the open-source community by making your code available for use. I spent two weeks carefully reading the software manual that you wrote, and I tested the FWI and RTM examples you provided on OBC Marmousi. I also added my simple bit of code into your project (https://github.com/daniel-koehn/DENISE-Black-Edition/pull/42).

As part of my research, I need to work with field data for the FWI and LSRTM of elastic waves. I have been trying to read your program source code for the past two weeks, and I have carefully studied the application of actual data in your article "https://onlinelibrary.wiley.com/doi/10.1002/nsg.12097". However, I am having some difficulty understanding how to modify` RTM-PSV.c`, `gra_obj_psv.c`, s`tf_psv`, and `psv.c` to incorporate real data into the framework.

With that said, I have a few questions for you:

1. Based on my preliminary understanding of your program, what do you think would be the main code changes required to use your code for actual data processing for the FWI and LSRTM of elastic waves?

2. Would it be possible for you to share some of your experience or code for elastic wave FWI and LSRTM for actual data processing?

Thank you very much for your time and expertise. I look forward to hearing back from you.

Best regards

Zhang

**Comment by daniel-koehn** [comment]
Dear Zhang,

Depending on your problem, these parts of the code do not require any modification for field data application. A successful FWI depends more on the estimation of an accurate initial model and reasonable data preprocessing. I produced an extensive tutorial video series on the application of FWI to a near-surface field dataset: [NGP Course “Seismic Full Waveform Inversion”](https://danielkoehnsite.wordpress.com/blog/ngp-course-seismic-full-waveform-inversion/) - with the caveat that the tutorials are currently only available in german. Perhaps they are still useful ...

Best regards,

Daniel

**Comment by zhangxiaoshuotttt** [comment]
Dear Daniel,

Thank you for your quick and informative response to my question. I spent most of today watching your[ NGP Course "Seismic Full Waveform Inversion"](https://danielkoehnsite.wordpress.com/blog/ngp-course-seismic-full-waveform-inversion/) tutorials (especially tutorials 8-13), and l found them to be incredibly helpful and inspiring.

Now that I have obtained the initial velocity model for field data, I am planning to use a code similar to `raw_data_sort.m` (if possible, and if not, a similar code) to segment and preprocess my **segy** data and obtain the corresponding observation system. I then plan to process **the segmented data(.su)** and **acquisition system** with the **DENISE Black Edition** for FWI and RTM.

Do you think this plan is reasonable? Could you please give me your advice on the next steps?

Thank you again for your guidance and expertise.

Best regards,

Zhang
