### ISSUE TITLE
 Error opening field data in DENISE despite reading with Madagascar-based FWI and RTM

### ISSUE THREAD

**Issue by zhangxiaoshuotttt** [daniel-koehn/DENISE-Black-Edition#45]
Hello,  @daniel-koehn 

First of all, I wanted to express my gratitude to you for recommending the [NGP Course “Seismic Full Waveform Inversion”](https://danielkoehnsite.wordpress.com/blog/ngp-course-seismic-full-waveform-inversion/) that has helped me get to this point. 

I am using DENISE for FWI and RTM based on field seismic data. To prepare the data, I sorted my shot data and velocity field in [Madagascar](https://www.reproducibility.org/wiki/Main_Page) and [SegyIO](https://github.com/slimgroup/SegyIO.jl). Following this, I used Madagascar and Python to convert my segy data into su format. I normalized my shot data trace by trace using Madagascar and I ensured that the maximum amplitude was 1, as observed in the examples provided. After these preprocessing steps, I obtained the `Source.dat` and `receiver.dat` files and estimated the frequency of the source wavelet.

However, when I try to execute DENISE on my data, I receive an error message stating “Field data could not be opened”. I have checked the data and was able to **read and plot** it using Madagascar, so I guess  that the issue is not with the data.
![Screenshot from 2023-06-09 23-02-15](https://github.com/daniel-koehn/DENISE-Black-Edition/assets/84370046/14918dff-8d7b-435b-8897-689cd3b74421)

When I checked the su file with Madagascar, it appears as shown in the attached picture. It appears that both of these files have incorrect headers. The top file is the forward model by DENISE, and the bottom file is my field data.
![Screenshot from 2023-06-09 23-11-10](https://github.com/daniel-koehn/DENISE-Black-Edition/assets/84370046/a87f302c-a5f7-41af-992b-2f55617d6ee3)

Could you please provide some guidance on what might be causing this issue and how it could be resolved? Any help would be greatly appreciated. If you need any additional information regarding my data, please do not hesitate to let me know. I would be happy to provide more details. Alternatively, you can also email me at ToZhangSS@163.com.

Best regards

Thank you!

**Comment by ADharaUTEXAS123007** [comment]
The software uses old su format. Use "suswapbytes" to convert the new su to old su format. DENISE will be able to read it.

**Comment by zhangxiaoshuotttt** [comment]
> The software uses old su format. Use "suswapbytes" to convert the new su to old su format. DENISE will be able to read it.

Thank you very much! Your advice has greatly helped me in solving this problem.

**Comment by zhangxiaoshuotttt** [comment]
Additionally, I have another solution to this problem. When using **Madagascar**, we can utilize the `sfsegywrite` function and set the `endian=n` parameter.
