### ISSUE TITLE
Some comfuse about SH modelling

### ISSUE THREAD

**Issue by lltfj1314sss** [daniel-koehn/DENISE-Black-Edition#47]
Hi Dr Kiehn,

When we modelling the SH wave in Denise-black-edition. How do we set the SH source in the source file？Should I select QUELLTYP=2? Look like we get the same modelling results using SH and PSV when we set  QUELLTYP=2? 

Thanks

Li

**Comment by daniel-koehn** [comment]
Hi Li, 

For SH modelling in DENISE Black-Edition, you have to set PHYSICS = 5 in the DENISE parameter file and QUELLTYP = 1 in the source file. In case of SH-FWI you also have to set QUELLTYPB = 1 in the DENISE parameter file.

Best regards,

Daniel

**Comment by lltfj1314sss** [comment]
Thank you for your rapid response. Set QUELLTYPB = 1 works. New question is the SH modellling seems like only output Y-direction data? How can we output the data of the same direction of source (SH direction)?

Best 
Li

**Comment by daniel-koehn** [comment]
Hi Li,

While the SH-data is denoted as "y-component" it is actually the data parallel to the SH-source excitation (z-component).

Best regards,

Daniel

**Comment by lltfj1314sss** [comment]
Hi Dr Koehn,

Got you, really appreciate it!!

Best regards

Li
