### ISSUE TITLE
Issues about boundary conditions.

### ISSUE THREAD

**Issue by zhangxiaoshuotttt** [daniel-koehn/DENISE-Black-Edition#48]
@daniel-koehn  
Hello, I am facing an issue while simulating an acoustic wave using a VSP geometry. I have observed that the CPML boundary conditions are not yielding the expected results. My model has a shape of 1280 (NX) * 610 (NY), with a DH of 5.0 and a `PHYSICS` parameter set to `2`. To understand CPML, I have been reading research papers. During my experimentation, I tried several parameters for my geometry, but I discovered that only when `FW=4`, I get some positive results. However, there are still some issues that need to be resolved. I also attempted to use other parameters, such as `npower` and `k_max_PML`, but it appears that they have little effect on the results.
[WaveField_Simulation.webm](https://github.com/daniel-koehn/DENISE-Black-Edition/assets/84370046/ec4dea6a-6736-4c00-b740-1e71860248a2)

**Comment by daniel-koehn** [comment]
Dear @zhangxiaoshuotttt, 

A PML thickness of 4 gridpoints (FW=4) is far too small. Typically, I use a FW = 20 or larger. The parameters DAMPING and FPML have to be adapted to your problem. A good starting point is to set DAMPING to the average P or S-wave velocity of the medium and FPML to the dominant frequency of the source wavelet. In some cases the PMLs can become unstable, so you have to tweak the DAMPING and FPML parameters a little bit more. 

Best regards,

Daniel

**Comment by zhangxiaoshuotttt** [comment]
Dear Daniel,

Thank you for your kind response. I apologize for the delayed reply. I have read some papers about CPML. After following your advice and conducting further tests, I realized that I had set the wrong `DAMPING` values. I have now resolved this issue.

Once again, I appreciate your assistance and wish you all the best.

Sincerely,
Zhang Shuo
