### ISSUE TITLE
SH RTM

### ISSUE THREAD

**Issue by lltfj1314sss** [daniel-koehn/DENISE-Black-Edition#52]
Dear Daniel,

I hope this email finds you well. My name is Chen. I am writing to inquire about the current version of the program and whether it supports SH RTM . I attempted to run the program recently, but it seems that I encountered difficulties in getting it to function properly for SH RTM purposes. 

Thank you very much for your attention to this inquiry. I look forward to your response.

Best regards,
Chen

**Comment by daniel-koehn** [comment]
Hi Chen,

Unfortunately, SH RTM is not implemented yet.

Best regards,

Daniel
